project:
  name: Rudrakhsa Segmentation Project
data:
  data_dir: data
  dataset_folder: RudrakshaDataset

model:
  name: UNet
  num_classes: 1
  smp_encoder: resnet18

loss:
  name: GeneralizedDiceLoss

experiment:
  name: Rudraksha Segmentation
  num_epochs: 100
  patience: 20
  image_size: 256
  batch_size: 8
  learning_rate: 0.001
  split_ratio: 0.2
  num_workers: 8
  accelerator: cuda # cpu, cuda, or mps
  devices: auto
  random_seed: 42
